#collect variables
Name = raw_input("What is your name?")
print(Name)
Name = ("Lou")
print(Name)
firstName = raw_input ("What is your firstname?")
lastName = raw_input ("What is your lastname?")
country = raw_input ("where do you live?")
country = (country.upper())
print ("\nHello " + firstName + " " + lastName + "\nYou live in " + country)
print("Op een dag komt " +firstName +" "  +lastName" in het laboratorium van Dr." )#+lastNameDoctor1 "en Dr." +lastNameDoctor2", 2 vrienden van zijn vader.")
#string manipulation
message = ("Hello world")
print(message.lower())
print(message.upper())
print(message.swapcase())
print(message.count("w"))
